# Generated by Django 4.1.7 on 2023-03-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe_subscribe_no_self_subscribe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
